name:                conjugate-programs
version:             0.1.0.0
github:              "DCMLab/conjugate-haskell-programs"
license:             BSD3
author:              "Christoph Finkensiep"
maintainer:          "chfin@chfin.de"
copyright:           "Christoph Finkensiep"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A simple DSL for probabilistic programming with conjugate models.

dependencies:
- base >= 4.7 && < 5
- containers
- vector
- microlens
- microlens-th
- transformers
- mtl
- mwc-random
- mwc-probability
- primitive
- math-functions

library:
  source-dirs: src

executables:
  conjugate-programs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conjugate-programs

tests:
  conjugate-programs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conjugate-programs
