name:                notebooks
version:             0.1.0.0
#github:              "chfin/notebooks"
license:             BSD3
author:              "Christoph Finkensiep"
maintainer:          "chfin@chfin.de"
copyright:           "Christoph Finkensiep"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
#description:         Please see the README on GitHub at <https://github.com/chfin/notebooks#readme>

dependencies:
- base >= 4.7 && < 5
- matplotlib
- text
- bytestring
- ihaskell
- temporary
- directory

library:
  source-dirs: src
